# Generated by Django 3.0.3 on 2020-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200918_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
