# Generated by Django 3.0.3 on 2020-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200919_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='seller',
            field=models.CharField(default='', max_length=64),
        ),
    ]
