# Generated by Django 3.0.3 on 2021-11-21 05:44

from django.db import migrations

def load_categories(apps,schema_editor):
    Cat= apps.get_model('news','Categories')
    categories=['Business','Entertainment','Health','Sports','General','Science','Technology']
    for category in categories:
        c= Cat(category=category)
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(load_categories)
    ]
