# Generated by Django 3.0.3 on 2020-11-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
