# Generated by Django 3.0.3 on 2020-11-17 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
