# Generated by Django 3.0.3 on 2020-11-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201117_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='subscribers',
        ),
    ]
