# Generated by Django 3.0.3 on 2020-11-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20201117_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
