# Generated by Django 3.0.3 on 2020-11-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_remove_categories_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
