# Generated by Django 3.0.3 on 2020-11-17 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='followers',
        ),
        migrations.AddField(
            model_name='categories',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
