# Generated by Django 3.0.3 on 2020-11-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20201117_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='cat_name',
            new_name='category',
        ),
    ]
